//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                 font-family: &quot;times new roman&quot;;
        ///                 line-height: 15px;
        ///                 font-size: 12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///				text-align:left;
        ///				padding:0;
        ///             }
        ///			 .table{
        ///			 	width: 100%;
        ///			 }
        ///			#header{
        ///				width: 100%;
        ///				text-align: right;
        ///			}
        ///			#drno{
        ///				margin-right: 200px;
        ///    			margin-top: 100px;
        ///			}
        ///			#TypeofStock{
        ///				text-align [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dr {
            get {
                return ResourceManager.GetString("Dr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///				
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///				text-align:left;
        ///				padding:10px;
        ///				text-align:center;
        ///             }
        ///			 .table{
        ///			 	width: 100%;
        ///			 }
        ///			h6{
        ///				padding: 0px;
        ///				margin: 0px;
        ///			}
        ///			#header{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string drReport {
            get {
                return ResourceManager.GetString("drReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///				
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///				text-align:left;
        ///				padding:10px;
        ///				text-align:center;
        ///				
        ///             }
        ///			 .table{
        ///			 	width: 100%;
        ///			 }
        ///			 h4{
        ///			 	 text-align: center;
        ///			 }
        ///			 h5{
        ///			 	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string incoming {
            get {
                return ResourceManager.GetString("incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                 font-family: &quot;times new roman&quot;;
        ///                 line-height: 15px;
        ///                 font-size: 12px;
        ///             }
        ///            .table, .table tr td, .table tr th {
        ///                text-align: left;
        ///                padding: 10px;
        ///                border-collapse: collapse;
        ///                border: 1px solid black;
        ///            }
        ///			 .table{
        ///			 	width: 100%;
        ///			 }
        ///			 #header{
        ///				margin-bottom: 0px; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Returns {
            get {
                return ResourceManager.GetString("Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                font-family:Arial;
        ///                line-height:15px;
        ///                font-size:12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                border-collapse:collapse;
        ///                border: 1px solid black;
        ///				text-align:left;
        ///				padding:10px;
        ///				text-align:center;
        ///             }
        ///			 .table{
        ///			 	width: 100%;
        ///			 }
        ///			 #Invoice{
        ///				width:40%%;
        ///				float:right;
        ///				padding:5px; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///
        ///        body {
        ///            font-family: &quot;times new roman&quot;;
        ///            line-height: 15px;
        ///            font-size: 12px;
        ///        }
        ///
        ///        .table, .table tr td, .table tr th {
        ///            /*border-collapse: collapse;
        ///            border: 1px solid black;*/
        ///            text-align: left;
        ///            padding: 0;
        ///        }
        ///
        ///        .table {
        ///            width: 100%;
        ///        }
        ///        #date{
        ///            width: 20%;
        ///            float: right;
        ///            text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string salesReport {
            get {
                return ResourceManager.GetString("salesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                 font-family: &quot;times new roman&quot;;
        ///                 line-height: 15px;
        ///                 font-size: 12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///				text-align:left;
        ///				padding:0;
        ///             }
        ///			 .table{
        ///			 	width: 100%;
        ///			 }
        ///			 #no{
        ///				text-align: right;
        ///				margin-top: 50px;
        ///				margin-right: 50px;
        ///			 }
        ///			 #Type{
        ///			 	text-align: center;
        ///			 }
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stocktranfer {
            get {
                return ResourceManager.GetString("Stocktranfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///         &lt;style type=&quot;text/css&quot;&gt;
        ///             body {
        ///                 font-family: &quot;times new roman&quot;;
        ///                 line-height: 15px;
        ///                 font-size: 12px;
        ///             }
        ///             .table, .table tr td, .table tr th {
        ///                 border-collapse: collapse;
        ///                 border: 1px solid black;
        ///                 text-align: left;
        ///                 padding: 10px;
        ///                 text-align: center;
        ///             }
        ///			 .table{
        ///			 	wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
    }
}
